### ISSUE TITLE
Event.pm missing in MANIFEST?

### ISSUE THREAD

**Issue by perw07** [AMS-IX/arpsponge#1]
I fetched the tar-file from AMS-IX website, but it wouldn't easily build. It was much easier once I had manually fetched ./lib/M6/ARP/Event.pm from GitHub.

I suspect that file is missing in the list of files to put into the tar-file, perhaps MANIFEST?

**Comment by sbakker** [comment]
Yep. That was indeed the problem. Thanks for spotting this.
