### ISSUE TITLE
Passive mode never sponging

### ISSUE THREAD

**Issue by MichaPMILL** [AMS-IX/arpsponge#10]
Hi,

I'm attempting to implement ARPSponge tool in passive mode (because there isn't any IP available on the concerned interface). 
For test, I has been decided to use the following rules : 

rate = 9
queuedepth = 9
learning = 360
pending = 10

The IP which aren't used are correctly detected but stay in PENDING(0) state. 
Is there a known issue to that problem ? 

Thank you,

**Comment by sbakker** [comment]
It's a bug indeed. I found the issue, will push a new version shortly.

**Comment by sbakker** [comment]
I just pushed a fix (3.24.1), thanks for reporting!
