### ISSUE TITLE
Errors reloading via init-script

### ISSUE THREAD

**Issue by perw07** [AMS-IX/arpsponge#2]
I'm running arpsponge on RHEL7 and have made some modifications to make it work (CLI output is not the same, some parsing needed modifying).

Reloading status from status-file sometimes misbehaves. I'm not actively programming perl since many years, and might need some help figuring this one out. I'll continue on my own meanwhile.

1) Problem reloading from init-script (excerpt, I'm running on about 15 different interfaces in total):
```
root@segotl2589# /etc/init.d/arpsponge reload
Saving state:
  interface=eth2.210   pid=4219   [Ok]
Stopping arpsponge(s):
  interface=eth2.210   pid=4219   terminated
Starting arpsponge(s):
  eth2.210   [Ok]
153.112.56.1: address out of range:q
153.112.56.18: address out of range
153.112.56.51: address out of range
153.112.56.69: address out of range
153.112.56.70: address out of range
153.112.56.71: address out of range
153.112.56.79: address out of range
153.112.56.87: address out of range
153.112.56.108: address out of range
153.112.56.110: address out of range
153.112.56.111: address out of range
153.112.56.172: address out of range
153.112.56.206: address out of range
153.112.56.244: address out of range
153.112.56.251: address out of range
old: total=62 static=1 alive=61 dead=0 pending=0
new: total=16 static=1 alive=15 dead=0 pending=0 changed=15
root@segotl2589#
```
The addresses complained about are probably the ones from the ARP table.

**--->> I just found the problem while writing this issue!** This line in the init-script:

`${BINDIR}/asctl -c load status "${rundir}/status"`
should probably instead be:
`${BINDIR}/asctl "--device=${DEVICE}" -c load status "${rundir}/status"`

**Comment by perw07** [comment]
The fix outlined in the original post seems to work well in RHEL7, also when used via systemd.

**Comment by sbakker** [comment]
Thanks for the report and suggested fix. I just applied them to the master branch. :+1:

**Comment by perw07** [comment]
To bad you didn't try it yourself first :)

The proper fix turned out to be `--interface=` and not `--device=`.

So sorry for the invoncenience, please update the fix.

/Per

**Comment by perw07** [comment]
See comment on issue; turns out I made the wrong fix.

/Per

**Comment by sbakker** [comment]
Haha, blind trust. I'll update the code.
