### ISSUE TITLE
Be more verbose about missing interface configuration

### ISSUE THREAD

**Issue by elonhub** [AMS-IX/arpsponge#8]
Hi,
arpsonge's [init script](https://github.com/AMS-IX/arpsponge/blob/master/init.d/arpsponge.sh#L157-L158) uses find to locate interface specific configuration in /etc/default/arpsponge/ using 'eth*' as pattern. Beeing the naive person i am, i tried to just put my actual interface name into /etc/default/arpsponge/ and wondered why nothing happened. To point the naive users nose into the right direction, the init script could print some informational message in that case:
```
diff --git a/init.d/arpsponge.sh b/init.d/arpsponge.sh
index bac9de8..360d3d2 100644
--- a/init.d/arpsponge.sh
+++ b/init.d/arpsponge.sh
@@ -163,6 +163,8 @@ start() {
         do
             start_sponge "$1" ${file}
         done
+    else
+        echo "${PROG}: No file matching 'eth*' found in @ETC_DEFAULT@/${PROG} for interface configuration"
     fi
     return 0
 }
```
I'm happy to do a pull request if that is of interest.

**Comment by sbakker** [comment]
Hi Leon,

Thanks for the heads-up. I'll have a look at it. Probably no need for a pull request.
The whole init setup is flaky, since, as you say, it looks for `eth*` patterns, and not all interfaces are necessarily named as such. There's a trick to call it `eth666` and mention the actual device name in the file, but that is indeed horrible.

I've been thinking of replacing this whole shell-based thing with proper YAML or JSON configuration, but that requires the daemon to do the parsing and forking...

**Comment by elonhub** [comment]
Hi Steven,
thanks for the fast reply. Having a more file like configuration would be nice and probably make porting easier. I went with specifying DEVICE= in some ethX and am totally fine with that. Its just that i was already cursing about systemd, when i should just have read the init script more thoroughly and notice my false assumption.
Thank you for still developing arpsponge.

**Comment by sbakker** [comment]
What I did for now is add some backward compatible change:

 1. Check if `@ETC_DEFAULT@/${PROG}` contains an `interfaces.d` sub-directory.
 2. If so, pick up *any* (non-hidden) file from the `interfaces.d` directory as a sponge configuration.
 3. If not, revert to the old behaviour (only `eth*` files from the `@ETC_DEFAULT@/${PROG}` directory).

The `find` command for the `interfaces.d` directory then becomes:

```
SPONGES=$(find "@ETC_DEFAULT@/${PROG}/interfaces.d" \
                -maxdepth 1 -type f -name '.*' | sort 2>/dev/null)
```
If I have a directory with:
```
$ ls -agG ./arpsponge/interfaces.d
total 8
drwxr-xr-x 2 4096 Mar  2 10:30 .
drwx------ 7 4096 Mar  2 10:32 ..
-rw-r--r-- 1    0 Mar  2 10:30 eth0
-rw-r--r-- 1    0 Mar  2 10:30 eth1
-rw-r--r-- 1    0 Mar  2 10:30 .hidden_file
-rw-r--r-- 1    0 Mar  2 10:30 .profile
-rw-r--r-- 1    0 Mar  2 10:30 tun0
-rw-r--r-- 1    0 Mar  2 10:30 wlp58s0
```
Then the find command will return:
```
$ find ./arpsponge/interfaces.d -maxdepth 1 -type f \! -name '.*' | sort
./arpsponge/interfaces.d/eth0
./arpsponge/interfaces.d/eth1
./arpsponge/interfaces.d/tun0
./arpsponge/interfaces.d/wlp58s0
```
Which is pretty much what we want: it would allow you to use the proper device name for the configuration file, even `defaults` if you want!

**Comment by sbakker** [comment]
I just pushed a new version of the init script to `master`. Tested it locally on my Debian box, seems to do the trick.

**Comment by elonhub** [comment]
I updated my git repo to dc89e32c7e4b2d4938cfa721d07d8762c815b55a, rebuild the package, installed and followed the migration hints in the manpage/POD and everything is working as expected. Thanks.

**Comment by sbakker** [comment]
Good to know!
